(module
  (import ())
  (import "")
  (import "" "")
  (import "" ())
  (import "" "" ())
  (import "" "" (func ))
  (import "" "" (table ))
  (import "" "" (memory ))
  (import "" "" (global ))
  (func (import))
  (func (import ""))
)
