(module
  (import ())
  (import "")
  (import "" "")
  (import "" ())
  (import "" "" ())
  (import "" "" (func ))
  (import "" "" (table ))
  (import "" "" (memory ))
  (import "" "" (global ))
  (func (import))
  (func (import ""))
  (func (import "env" "f1") (import "env" "f2"))
  (import "" (func))
  (import "" (item ))
  (import "" (item ""))
  (import "" (item (func)))
  (import "test" (item "global->1") (global $global->1 i32))
  (import "" (item "") (item "" (func)))
  (import "" (item "" (func)) (item ""))
  (import "" (item "" (func)) (func))
)
