(module (memory 0))
(module (memory 0 0))
(module (memory (data)))
(module (memory (data "x")))
(module (memory i32 0))
(module (memory i64 0 1))
(module (memory 0 (pagesize 1)))
(module (memory 0 1 (pagesize 65536)))
