(module
  (func
                      block
                                      block
                                                      block
                                                      end
                                      end
                      end
  )
)
