packages:
  - bindings/pkg
  - docs
  - playground

allowBuilds:
  esbuild: false

overrides:
  "@hpcc-js/wasm": "npm:@hpcc-js/wasm-graphviz"
  vscode-languageserver-protocol: "^3.18.2"

patchedDependencies:
  d3-graphviz: patches/d3-graphviz.patch
