import { IndentAction } from '@codingame/monaco-vscode-api/vscode/vs/editor/common/languages/languageConfiguration'
import type * as monaco from '@codingame/monaco-vscode-editor-api'

export const monacoOptions: monaco.editor.IStandaloneEditorConstructionOptions = {
  minimap: { enabled: false },
  fontFamily: '"Google Sans Code", monospace',
  fontSize: 16,
  lineHeight: 28,
  tabSize: 2,
  codeLens: false,
  automaticLayout: true,
}

export function registerLanguage(monaco: typeof import('@codingame/monaco-vscode-editor-api')) {
  monaco.languages.register({ id: 'wat', extensions: ['.wat'] })
  monaco.languages.setMonarchTokensProvider('wat', {
    brackets: [{ open: '(', close: ')', token: 'delimiter.parenthesis' }],
    keywords: [
      'array',
      'block',
      'catch',
      'catch_ref',
      'catch_all',
      'catch_all_ref',
      'data',
      'declare',
      'elem',
      'else',
      'end',
      'export',
      'field',
      'final',
      'func',
      'global',
      'if',
      'import',
      'item',
      'local',
      'loop',
      'memory',
      'module',
      'mut',
      'null',
      'offset',
      'pagesize',
      'param',
      'rec',
      'ref',
      'result',
      'shared',
      'start',
      'struct',
      'sub',
      'table',
      'tag',
      'then',
      'try_table',
      'type',
      'unshared',
    ],
    typeKeywords: [
      'i32',
      'i64',
      'f32',
      'f64',
      'v128',
      'i8',
      'i16',
      'any',
      'eq',
      'i31',
      'none',
      'nofunc',
      'exn',
      'noexn',
      'extern',
      'noextern',
      'cont',
      'nocont',
      'anyref',
      'eqref',
      'i31ref',
      'structref',
      'arrayref',
      'nullref',
      'funcref',
      'nullfuncref',
      'exnref',
      'nullexnref',
      'externref',
      'nullexternref',
      'contref',
      'nullcontref',
    ],
    tokenizer: {
      root: [
        [
          /[a-z_$][\w.$]*/,
          {
            cases: {
              '@typeKeywords': 'type.identifier',
              '@keywords': 'keyword',
              '@default': 'operators',
            },
          },
        ],
        [/\$[\w.$-_]+/, 'variable.name'],
        { include: '@whitespace' },
        [/[()]/, '@brackets'],
        [/\d*\.\d+([eE][\-+]?\d+)?/, 'number.float'],
        [/0[xX][0-9a-fA-F]+/, 'number.hex'],
        [/\d+/, 'number'],
        [/"([^"\\]|\\.)*$/, 'string.invalid'],
        [/"/, { token: 'string.quote', bracket: '@open', next: '@string' }],
      ],
      comment: [
        [/[^;)]+/, 'comment'],
        [/;\)/, 'comment', '@pop'],
        [/[;)]/, 'comment'],
      ],
      string: [
        [/[^\\"]+/, 'string'],
        [/"/, { token: 'string.quote', bracket: '@close', next: '@pop' }],
      ],
      whitespace: [
        [/[ \t\r\n]+/, 'white'],
        [/\(;/, 'comment', '@comment'],
        [/;;.*$/, 'comment'],
      ],
    },
  })
  monaco.languages.setLanguageConfiguration('wat', {
    comments: {
      lineComment: ';;',
      blockComment: ['(;', ';)'],
    },
    brackets: [['(', ')']],
    autoClosingPairs: [
      { open: '{', close: '}' },
      { open: '[', close: ']' },
      { open: '(', close: ')' },
      { open: '"', close: '"' },
      { open: '(*', close: '*)', notIn: ['string'] },
    ],
    surroundingPairs: [
      { open: '{', close: '}' },
      { open: '[', close: ']' },
      { open: '(', close: ')' },
      { open: '"', close: '"' },
      { open: '(*', close: '*)' },
    ],
    indentationRules: {
      increaseIndentPattern: /^((?!;;).)*\([^)"'`]*$/,
      decreaseIndentPattern: /^((?!.*?\(;).*;\))?\s*\).*$/,
    },
    onEnterRules: [
      {
        beforeText: /^.*\([^\)]*$/,
        afterText: /^\s*\).*$/,
        action: {
          indentAction: IndentAction.IndentOutdent,
          appendText: '\t',
        },
      },
      {
        beforeText: /^\s*;;; /,
        action: {
          indentAction: IndentAction.None,
          appendText: ';;; ',
        },
      },
      {
        beforeText: /^\s*;;;/,
        action: {
          indentAction: IndentAction.None,
          appendText: ';;;',
        },
      },
    ],
  })
}
