name: vscode-extension

on:
  release:
    types: [published]

jobs:
  vscode:
    runs-on: ubuntu-latest
    steps:
      - shell: pwsh
        run: |
          $headers = @{
            "Accept" = "application/vnd.github+json"
            "Authorization" = "Bearer ${{ secrets.VSCODE_EXT_REPO_TOKEN }}"
            "X-GitHub-Api-Version" = "2022-11-28"
          }
          $body = @{
            "ref" = "main"
            "inputs" = @{
              "semver" = "minor"
            }
          } | ConvertTo-Json
          Invoke-WebRequest -Uri "https://api.github.com/repos/g-plane/vscode-wasm/actions/workflows/release.yml/dispatches" -Method Post -Headers $headers -Body $body
